### PR TITLE
Completed the project setup

### PR DESCRIPTION
**Pull request by Palak-2109**
Issue: 1

**https://github.com/opencodeiiita/Collaborative-App/issues/1** 

### Reason of Bug
Setup

### Small Description of Changes Performed
Added screenshot

### Screenshots
Collaborative_app_setup_palak_ahuja

### CODE REVIEW

**Comment by Palak-2109** [comment]
I have also added myself in contributor.xml ..Do I need to make a separate PR for both the issues? @VarunT11

**Comment by VarunT11** [comment]
@Palak-2109 Yes, you need to make a separate PR for both issues. For this Pull Request, just remove the changes performed in the `contributor.xml` file and commit and push the changes. For the other issue, create a new Pull Request.

**Comment by Palak-2109** [comment]
ohkkk

**Comment by Palak-2109** [comment]
I have removed the changes from the contributor.xml file. Please review this PR now and I will make another one for that @VarunT11

**Comment by VarunT11** [comment]
@Palak-2109 Please update the file name of the Screenshot added with your **GitHub User ID** only.

**Pull request closed without merging**
