### PR TITLE
added my name in contributor.xml

### PR DESCRIPTION
**Pull request by osho-20**
Issue: 10

**Issue Reference:**  https://github.com/opencodeiiita/Collaborative-App/issues/10

### Reason of Bug
`Applicable only in Issues where a bug was reported`
`Specify the reasons of the encountered bug`

Small Description of Changes Performed
added my name in contributor.xml

Screenshots
`Add Screenshots in this Section of the Updated Features`
Screenshot from 2021-10-04 16-13-11

### PS
`Add any Post-Script messages for the mentors

### CODE REVIEW

**Comment by VarunT11** [comment]
@osho-20 Please provide the link to the issue as asked in the Template

**Comment by osho-20** [comment]
okk

**Comment by osho-20** [comment]
i have to make another pill request?

**Comment by VarunT11** [comment]
@osho-20 No you just need to update the description of this Pull Request. No need to create a new Pull Request! Just add the Link after **Issue Reference:** .

**Comment by osho-20** [comment]
done sir

**Pull request merged**
