### PR TITLE
added my details

### PR DESCRIPTION
**Pull request by hotblooded058**
Issue: 10

added my details

### CODE REVIEW

**Comment by VarunT11** [comment]
@hotblooded058 Please provide the link to the issue as required in the PR Template.

**Comment by hotblooded058** [comment]
Issue: 80

Issue Reference: #80
added my details

**Comment by VarunT11** [comment]
@hotblooded058 Please remove the screenshot of the setup task from this pull request, and create a different pull request for the same issue, otherwise, you will not receive the points of that issue!

**Comment by VarunT11** [comment]
@hotblooded058 Please create a new Pull Request as this PR is being closed now.
Do follow the following steps while creating a new Pull Request:
- Rebase your `main` branch with the `main` branch of the main repository.
- Create different branches for different issues and create Pull Requests from these different branches only else you will not receive points for all the issues solved.
- Make sure that the files changed while creating the Pull Requests are related to that Issue only.

**Pull request closed without merging**
