### PR TITLE
added my name

### PR DESCRIPTION
**Pull request by 99anjali**
Issue:10

#10 

### Small Description of Changes Performed
added my name in contributor.xml

### Screenshots
Capture

### CODE REVIEW

**Comment by 99anjali** [comment]
@VarunT11 sir please check this pr.

**Comment by VarunT11** [comment]
@99anjali You did not receive the points as you did not follow the **exact** Template. Please create a new Pull Request while following the **exact** Template. Merge the `main` branch before creating the same.

**Comment by 99anjali** [comment]
do i have to include my name again?

**Comment by VarunT11** [comment]
@99anjali Yes create a new Pull Request for the same!

**Pull request merged**
