### PR TITLE
Updated contributor.xml

### PR DESCRIPTION
**Pull request by Yuvatejasvi**
Issue: 10

Issue Reference: #10

 

 Small Description of Changes Performed
added my name in contributor.xml

Screenshots
Screenshot 2021-10-05 at 12 26 35 AM

### CODE REVIEW

**Comment by VarunT11** [comment]
@Yuvatejasvi Please provide a link to the Issue as required in the PR Template.

**Comment by Yuvatejasvi** [comment]
> @Yuvatejasvi Please provide a link to the Issue as required in the PR Template.

yes sir, done

**Comment by VarunT11** [comment]
@Yuvatejasvi It seems that your name was not added, or was removed while resolving the conflicts. Please add your name again to the file.

**Comment by Yuvatejasvi** [comment]
@VarunT11  sir , i have resolved all my conflicts and added my name again .

**Pull request closed without merging**
